### ISSUE TITLE
Can't restart

### ISSUE THREAD

**Issue by lichstam** [krawaller/swordle#1]
Hey!

Nicely done :)

There is a small bug. After winning/getting the right word I'm unable to restart the game :/

<img width="421" alt="Screenshot 2022-01-24 at 20 55 08" src="https://user-images.githubusercontent.com/34944192/150854839-efdb7953-6553-4da1-a0e3-a1212b0ea615.png">

**Comment by litenjacob** [comment]
I know it's lacking in the onboarding department, but I _think_ you're not supposed to be able to restart the game – you'll have to come back tomorrow. I see I definitely need to explain this better, but initially took the liberty of skipping this since it felt like everyone had played the original [Wordle](https://www.powerlanguage.co.uk/wordle/) by now 😅

**Comment by lichstam** [comment]
haha, oops :), well i guess it makes sense then

**Comment by litenjacob** [comment]
For a very lax definition av sense at least 🙈 But you raising this issue points to a adding an explanation making even  _more_ sense 😅
